### ISSUE TITLE
Mapping to "P-15" for ID.RA-1

### ISSUE THREAD

**Issue by itauditor007** [usnistgov/PrivacyFrmwkResources#13]
Please include the following details about the resource in your “Issue” to ensure the contributor is informed about this feedback.

**Resource identifier:** - See subject.  Is mapping in csf-pf-to-sp800-53r5-mappings.xlsx
**Contributor’s GitHub username:** @[enter username]:  @kboeckl

**Feedback:**  What is proper "P" family mapping?  Both PE and PM families have a "-15" control.  Based on alpha sequence in mappings seems likely is PM-15 vice PE-15, but confirming and recommending update to XLSx.

**Comment by kboeckl** [comment]
Hi @itauditor007 - thank you very much for bringing this typo to my attention. You're right, we meant to say "PM-15" here. I've fixed this error and uploaded a corrected version of the Excel to reflect this. https://github.com/usnistgov/PrivacyFrmwkResources/raw/master/resources/NIST%20SP%20800-53%20Crosswalk/csf-pf-to-sp800-53r5-mappings.xlsx
