### ISSUE TITLE
Annual resource verification - LINDDUN privacy threat modeling framework

### ISSUE THREAD

**Issue by kboeckl** [usnistgov/PrivacyFrmwkResources#15]
Hi @kimwuyts. Since it’s now been one year since you originally contributed your resource, the [LINDDUN privacy threat modeling framework](https://www.nist.gov/privacy-framework/linddun-privacy-threat-modeling-framework), it’s now time for you to verify its accuracy and relevancy, per the contributor responsibilities described in our [Operating Rules](https://www.nist.gov/privacy-framework/resource-repository/operating-rules). Please respond to this “issue” with the status of your resource: either confirming that the contribution remains accurate and relevant, or that you need to make updates to maintain its accuracy and relevancy (e.g., to reflect recent changes to a source document). In the case that updates are needed, you can share updates to your resource via pull requests. Please let me know if you have any questions. Note: NIST reserves the right to reject or remove contributions from the repository if the contributor does not perform this annual verification. Thank you, again, for sharing your resource!

**Comment by kimwuyts** [comment]
Hi @kboeckl, this contribution remains accurate and relevant.

**Comment by kboeckl** [comment]
Thank you for the quick reply, @kimwuyts! That's great. I'll close this issue, then. Hope you're doing well!
