### ISSUE TITLE
Annual resource verification - PII Inventory Dashboard

### ISSUE THREAD

**Issue by kboeckl** [usnistgov/PrivacyFrmwkResources#16]
Hi @ondrae, @peterrowland, @igorkorenfeld, and @nikzei. Since it’s been one year since you originally contributed your resource, the [PII Inventory Dashboard](https://www.nist.gov/privacy-framework/pii-inventory-dashboard), it’s now time for you to verify its accuracy and relevancy, per the contributor responsibilities described in our Operating Rules. Please respond to this “issue” regarding the status of your resource, by either confirming that the contribution remains accurate and relevant, or that you need to make updates to maintain its accuracy and relevancy (e.g., to reflect recent changes to a source document). In the case that updates are needed, you can share updates to your resource via pull requests. Please let me know if you have any questions. Note: NIST reserves the right to reject or remove contributions from the repository if the contributor does not perform this annual verification. Thank you, again, for sharing your resource.

**Comment by ondrae** [comment]
Hello @kboeckl, we have no updates needed now. In a few months we will have a whole new version of the tool available. We'll send in a pull request then with all the new info and links for your review. Thanks for checking in.

**Comment by kboeckl** [comment]
@ondrae That's great, thanks for the quick response and the heads up on future updates. Much appreciated -- I'll close this issue then!
