### ISSUE TITLE
Broken link in NIST SP 800-160 Vol 1

### ISSUE THREAD

**Issue by jrado-wi** [usnistgov/PrivacyFrmwkResources#6]
Please include the following details about the resource in your “Issue” to ensure the contributor is informed about this feedback.

**Resource identifier:** NIST SP 800-160 Vol 1
**Contributor’s GitHub username:** @kboeckl

**Feedback:** 

It looks like there is a broken link on page 9, under this text: "Resilient Military Systems and
the Advanced Cyber Threat." 

Here's the link that's not working: https://www.acq.osd.mil/dsb/reports/2010s/ResilientMilitarySystemsCyberThreat.pdf

I apologize if this isn't an appropriate way to report this issue! This is my first time attempting to do this. Thanks!

**Comment by kboeckl** [comment]
Hi @jrado-wi! Thank you for sharing this, and my apologies for the delayed response. While I'd be hesitant to say this is not "an appropriate way to report this issue", I would say that the best way to communicate with us (NIST) about the content of NIST SP 800-160, Vol 1, would be by emailing the NIST leads for this publication at: [sec-cert@nist.gov](mailto:sec-cert@nist.gov). This GitHub repository is focused on these publications' relationship to the NIST Privacy Framework to support its implementation.

I've passed your note along to the appropriate NIST team so they can process your comment. If you'd like to follow up with them, you can contact them at the address I provided earlier. If you have further questions, please let me know, and if not, I'll close this issue.

Thank you, again, for sharing your comment with us!
